[book]
authors = ["Andrew T. Polonsky <apolon@sandia.gov>"]
description = "Automated tools for 3D analysis."
language = "en"
multilingual = false
src = "src"
title = "User Guide"

[preprocessor.cmdrun]
